export const LOG_LEVEL = "LOG_LEVEL";

export const REDIS_QUEUE_NAME = "REDIS_QUEUE_NAME";
export const REDISCLOUD_URL_VAR = "REDISCLOUD_URL_VAR";
export const REDIS_CONNECTION_STRING = "REDIS_CONNECTION_STRING";

export const DATABASE_CONNECTION_STRING = "DATABASE_CONNECTION_STRING";
export const DATABASE_URL_VAR = "DATABASE_URL_VAR";
export const DATABASE_SCHEMA = "DATABASE_SCHEMA";
